### ISSUE TITLE
Focus Puller no longer working in HDRP 2019.1

### ISSUE THREAD

**Issue by gekigengar** [keijiro/PostProcessingUtilities#3]
In 2019.1 post processing stack is now integrated with HDRP.

`UnityEngine.Rendering.PostProcessing` no longer available.

**Comment by keijiro** [comment]
I slightly updated the project settings to avoid package upgrade errors. Please try the latest version. It worked on my side.

**Comment by JexD** [comment]
still does'nt seem to be working, 

Assets\Runtime\FocusPuller.cs(2,29): error CS0234: The type or namespace name 'PostProcessing' does not exist in the namespace 'UnityEngine.Rendering' (are you missing an assembly reference?)

Assets\Runtime\FocusPuller.cs(13,9): error CS0246: The type or namespace name 'DepthOfField' could not be found (are you missing a using directive or an assembly reference?)

Assets\Runtime\FocusPuller.cs(14,9): error CS0246: The type or namespace name 'PostProcessProfile' could not be found (are you missing a using directive or an assembly reference?)

Assets\Runtime\FocusPuller.cs(15,9): error CS0246: The type or namespace name 'PostProcessVolume' could not be found (are you missing a using directive or an assembly reference?)

using 2019.2.12f1
